<div class="form-box">
<div class="form-title-wrap">
    <h3 class="title"><?=T::paymentmethod?></h3>
</div><!-- form-title-wrap -->
<div class="form-content">

<?php 

if(isset($_SESSION['user_type'])){
    if($_SESSION['user_type'] == 'customers'){
 ?>
<style type="text/css">
    .gateways_wallet-balance{display: none!important;}
</style>
<?php } } else {?>
<style type="text/css">
    .gateways_wallet-balance{display: none!important;}
</style>
<?php }?>
    <!-- new code by ak -->
    
                    <div class="form-content">
                        <div class="check-mark-tab text-center pb-4 col-lg-12 row">
                            <ul class="nav nav-tabs gateways" id="myTab" role="tablist">

                    <?php
                    // dd($_SESSION['user_type']);die;
                            // Your API Key and secret
                        // $apiKey = "f62d45b726f74158f7f6da081b892d27";
                        // $Secret = "79dd82ddee";

                        // Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
                        //$signature = hash("sha256", $apiKey.$Secret.time());


                        foreach ($app->payment_gateways as $items => $item){
          
                                // hide wallet balance payment option if user is not logged in
                        if(!isset($_SESSION['user_login']) == true) { echo "<style>.gateway_wallet-balance{display:none}</style>"; }?>

                                <!--< ?php if ($item->title == "installments") { ?> -->

                              <!--  <li class="nav-item  pt-4 col-lg-4 col-md-4 m-0 p-2 gateways_< ?=$item->title?>">-->
                              <!--      <a class="nav-link aaf < ?php if (str_replace('-', ' ', $item->title) == "payment with credit card") { echo "active"; }?> " style="background:#fff;" 
                                             data-toggle="tab" href="#< ?=$item->title ?>" payment-method="< ?=$item->title ?>" role="tab" aria-controls="< ?=$item->title ?>" aria-selected="true" 
                                               onclick="add_attributes_on_btn()">-->
                              <!--          <i class="la la-check icon-element"></i>-->
                              <!--          <img src="< ?=root.theme_url?>assets/img/gateways/< ?=$item->title ?>.png" alt="< ?=$item->title ?>" class="img-fluid w-75">-->
                              <!--          <span class="d-block pt-2 font-size-13">< ?php if ($item->title == "pay-later") { } else {} ?>< ?=str_replace('-', ' ', $item->title)?></span>-->
                                       
                              <!--      </a>-->
                              <!--  </li>-->

                              <!--< ?php }else{ ?>-->

                              <!--  <li class="nav-item pt-4 col-lg-4 col-md-4 m-0 p-2 gateways_< ?=$item->title?>">-->
                              <!--      <a class="nav-link aaf < ?php if (str_replace('-', ' ', $item->title) == "payment with credit card") { echo "active"; }?> " style="background:#fff;" data-toggle="tab" href="#< ?=$item->title ?>" payment-method="< ?=$item->title ?>" role="tab" aria-controls="< ?=$item->title ?>" aria-selected="true" onclick="remove_attributes_on_btn()">-->
                              <!--          <i class="la la-check icon-element"></i>-->
                              <!--          <img src="< ?=root.theme_url?>assets/img/gateways/< ?=$item->title ?>.png" alt="< ?=$item->title ?>" class="img-fluid w-75">-->
                              <!--          <span class="d-block pt-2 font-size-13">< ?php if ($item->title == "pay-later") { } else {} ?>< ?=str_replace('-', ' ', $item->title)?></span>-->
                              <!--      </a>-->
                              <!--  </li>-->

                              <!--< ?php }?>-->
                              
                              
                                <li class="nav-item pt-4 col-lg-4 col-md-4 m-0 p-2 gateways_<?=$item->title?>">
                                    <a class="nav-link aaf <?php if (str_replace('-', ' ', $item->title) == "payment with credit card") { echo "active"; }?> " style="background:#fff;" data-toggle="tab" href="#<?=$item->title ?>" payment-method="<?=$item->title ?>" role="tab" aria-controls="<?=$item->title ?>" aria-selected="true">
                                        <i class="la la-check icon-element"></i>
                                        <img src="<?=root.theme_url?>assets/img/gateways/<?=$item->title ?>.png" alt="<?=$item->title ?>" class="img-fluid w-75">
                                        <span class="d-block pt-2 font-size-13"><?php if ($item->title == "pay-later") { } else {} ?><?=str_replace('-', ' ', $item->title)?></span>
                                    </a>
                                </li>
                              
                              <?php } ?>  
                               <!--<input class="form-check-input payment_gateway mx-auto" type="hidden" name="payment_gateway" value="payment-with-credit-card" required>-->
                               
                               
                               
     <!--/////////////// Feras Implementation /////////////// -->
                <!--?php
                    foreach ($app->payment_gateways as $items => $item){
                     if(!isset($_SESSION['user_login']) == true) { echo "<style>.gateway_wallet-balance{display:none}</style>"; }
                ?>
                            <li class="nav-item pt-4 col-lg-4 col-md-4 m-0 p-2 gateways_< ?=$item->title?>">
                                <a class="nav-link aaf < ?php if (str_replace('-', ' ', $item->title) == "payment with credit card") { echo "active"; }?> " 
                                      style="background:#fff;" id="< ?=$item->title?>-tab" data-toggle="tab" href="#< ?=$item->title?>" 
                                         payment-method="< ?=$item->title?>" role="tab" aria-controls="< ?=$item->title?>" aria-selected="false">
                                    
                                    <i class="la la-check icon-element"></i>
                                    <img src="< ?=root.theme_url?>assets/img/gateways/< ?=$item->title ?>.png" alt="< ?=$item->title ?>" class="img-fluid w-75">
                                    <span class="d-block pt-2">
                                        < ?php if ($item->title == "pay-later") 
                                                { } else {?>
                                            < ?=T::paywith?> 
                                        < ?php } ?> 
                                        <strong>< ?=str_replace('-', ' ', $item->title)?></strong>
                                    </span>
                                </a>
                            </li>
                < ?php } ? -->
<!--/////////////// END Feras Implementation /////////////// -->
                               
                    </div><!-- end section-tab -->
                    
                    
                        <!--<script type="text/javascript">-->
                        <!--    $('a.aaf').click(function(){-->
                        <!--        var payment_method = $(this).attr('payment-method');-->
                                <!--// alert(payment_method);-->
                        <!--        $('.payment_gateway').val(payment_method);-->
                        <!--    });-->
                        <!-- function add_attributes_on_btn(){-->
                        <!--    $('.attr_for_tabby').removeAttr('type');-->
                        <!--    $('.attr_for_tabby').attr("type","button");-->
                        <!--    $('.attr_for_tabby').attr("onclick","submit_tabby_req()");-->
                        <!-- }-->
                        <!-- function remove_attributes_on_btn(){-->
                        <!--    $('.attr_for_tabby').removeAttr("type");-->
                        <!--    $('.attr_for_tabby').removeAttr("onclick");-->
                        <!--    $('.attr_for_tabby').attr("type","submit");-->
                        <!--    }-->
                        <!--</script>-->
                       
                   
               
                <!--<script src="https://techydevs.com/demos/trizen/html/js/bootstrap.min.js"></script>-->
                
                <!--?php include views."assets/js/bootstrap.min.js"; ?-->



<!--/////////////// Feras Implementation installments ------ tabs /////////////// -->

     <style>                      
        input[type="radio"]:checked + .card {
            /* background: linear-gradient(298deg,#FFAA02 ,#8C39E0); */
            border:green 2px solid;
            /* letter-spacing: -0.24px; */
          };
      </style>
                          
<div class="tab-content">
        <div class="tab-pane fade" id="installments" role="tabpanel" aria-labelledby="installments-tab">
            <div class="contact-form-action">
                       <label class="label-text">Please choose installement channel</label>
                        <div class="row" >
                            <div class="col-lg-6 responsive-column">
                                <label style="width: 100%; margin: 0; padding: 0;" >
                                    <input type="radio" name="tri" value="1" class="d-none" />
                                    <div class="col-lg-12 card card-block d-flex p-2" style="border-radius: .5rem; width:100%;">
                                        <div class="pt-3 pb-1">
                                                    <img src="https://rivatrip.com/app/themes/default/assets/img/tabby-logo.png" alt="tabby" style="width:100px; height: 41px;">
                                                    <span class="d-block pt-2 font-size-13">
                                                       <?=T::interesttext?> 787.5. AED.
                                                    </span>
                                        </div>
                                    </div>
                                </label>
                            </div>
                            <div class="col-lg-6 responsive-column">
                                <label style="width: 100%; margin: 0; padding: 0;" >
                                    <input type="radio" name="tri" value="2" class="d-none" />
                                    <div class="col-lg-12 card card-block d-flex  p-2" style="border-radius: .5rem; width:100%;">
                                        <div class="pt-3 pb-1">
                                                    <img src="https://rivatrip.com/app/themes/default/assets/img/payment-img.png" alt="amazone-installments" style="width:100px; height: 41px;">
                                                    <span class="d-block pt-2 font-size-13">                                                                  
                                                    Customize your installments through your credit card.
                                                    </span>
                                        </div>
                                    </div>
                                </label>
                            </div>
                        </div>
            </div>
       </div>      
       <div class="tab-pane fade" id="paypal" role="tabpanel" aria-labelledby="paypal-tab">
       </div>
       <div class="tab-pane fade" id="pay-later" role="tabpanel" aria-labelledby="pay-later-tab">
       </div>
       <div class="tab-pane fade" id="bank-transfer" role="tabpanel" aria-labelledby="bank-transfer-tab">
       </div>
       <div class="tab-pane fade" id="payment-with-credit-card" role="tabpanel" aria-labelledby="payment-with-credit-card-tab">
       </div>
</div>     
        
     <script src="<?=root?><?=theme_url?>assets/js/bootstrap.min.js"></script>

            
   </ul>
 </div><!-- end form-content -->
 
 <script>
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
      var target = $(e.target).attr("href") // activated tab
    //   alert(target);
     //  alert("target");
     
     if ( target == '#installments')
     {
         alert(target);
     }
});


 $("input[name='tri']").change(function() {
    var radioValue = $(this).val();
    //console.log(radioValue);
  //  alert(radioValue);
    
    if(radioValue == 1) {
       alert('tabby'); 
    }
    
  });



// $(document).ready(function(){
//     $('a[data-toggle="tab"]').on('show.bs.tab', function(e) {
//         localStorage.setItem('activeTab', $(e.target).attr('href'));
//     });
//     var activeTab = localStorage.getItem('activeTab');
//     if(activeTab){
//         $('#credit-card-tab a[href="' + activeTab + '"]').tab('show');
//       //  alert('feras');
//       //  $('#myTab a[href="' + activeTab + '"]').tab('show');
//     } else {
//       // alert('nooo');
//     }
// });


</script>
 
       


<!--<script src="https://techydevs.com/demos/trizen/html/js/bootstrap.min.js"></script>-->

<!--script>
    $(document).ready(function(){
    $('a[data-toggle="tab"]').on('show.bs.tab', function(e) {
        localStorage.setItem('activeTab', $(e.target).attr('href'));
    });
    var activeTab = localStorage.getItem('activeTab');
    if(activeTab){
        $('#credit-card-tab a[href="' + activeTab + '"]').tab('show');
      //  alert('feras');
      //  $('#myTab a[href="' + activeTab + '"]').tab('show');
    } else {
       // alert('nooo');
    }
});
</script-->

<!--/////////////// END Feras Implementation installments ------ tabs /////////////// -->

   
</div>
</div><!-- end form-box -->