

<div class="form-box">
<div class="form-title-wrap">
    <h3 class="title"><?=T::paymentmethod?></h3>
</div><!-- form-title-wrap -->

<style>
    #spinner-div {
          position: fixed;
          display: none;
          width: 100%;
          height: 100%;
          top: 0;
          left: 0;
          text-align: center;
          background-color: rgba(255, 255, 255, 0.8);
          z-index: 2;
        }
        
    #alert-div{
          /*position: fixed;*/
          display: none;
          /*z-index: 2;*/
        }
</style>

<!--<div class="preloader" id="preloader" >-->
<!--    <div class="loader">-->
<!--        <svg class="spinner" viewBox="0 0 50 50">-->
<!--            <circle class="path" cx="25" cy="25" r="20" fill="none" stroke-width="5"></circle>-->
<!--        </svg>-->
<!--    </div>-->
<!--</div>-->

<!--<div class="spinner-border" role="status" style="display: none;">-->
<!--  <span class="visually-hidden">Loading...</span>-->
<!--</div>-->

<div id="spinner-div" class="pt-5">
  <div class="spinner-border text-primary" role="status">
  </div>
</div>


<div class="accordion-item"> <!--accordion-->
  <div id="content-3" class="accordion-content accordion-collapse collapse" data-bs-parent="#myAccordion">


<div class="form-content">

<?php 

if(isset($_SESSION['user_type'])){
    if($_SESSION['user_type'] == 'customers'){
 ?>
<style type="text/css">
    .gateways_wallet-balance{display: none!important;}
</style>
<?php } } else {?>
<style type="text/css">
    .gateways_wallet-balance{display: none!important;}
</style>
<?php }?>
    <!-- new code by ak -->
    
                    <div class="form-content">
                        <div class="check-mark-tab text-center pb-4 col-lg-12 row">
                            
                            <div id="alert-div" class="pt-5">
                               <div class="alert alert-danger"><?=T::tabby_message?></div>
                            </div>
                            
                            <ul class="nav nav-tabs gateways" id="myTab" role="tablist">

                    <?php
                    // dd($_SESSION['user_type']);die;
                            // Your API Key and secret
                        //$apiKey = "f62d45b726f74158f7f6da081b892d27";
                       // $Secret = "79dd82ddee";

                            // Signature is generated by SHA256 (Api-Key + Secret + Timestamp (in seconds))
                       // $signature = hash("sha256", $apiKey.$Secret.time());

 
                        foreach ($app->payment_gateways as $items => $item){
          
                                // hide wallet balance payment option if user is not logged in
                        if(!isset($_SESSION['user_login']) == true) { echo "<style>.gateway_wallet-balance{display:none}</style>"; }?>

                                 <li class="nav-item pt-4 col-lg-4 col-md-4 m-0 p-2 gateways_<?=$item->title?>">
                                    <a class="nav-link aaf <?php if (str_replace('-', ' ', $item->title) == "payment with credit card") { echo "active"; }?> " style="background:#fff;" data-toggle="tab" href="<?=$item->title ?>" payment-method="<?=$item->title ?>" role="tab" aria-controls="<?=$item->title ?>" aria-selected="true">
                                      <!--<a class="nav-link aaf" style="background:#fff;" -->
                                      <!--    data-toggle="tab" href="<?=$item->title ?>" payment-method="<?=$item->title ?>" role="tab" aria-controls="<?=$item->title ?>" aria-selected="true">-->
                                         <i class="la la-check icon-element"></i>
                                        <img src="<?=root.theme_url?>assets/img/gateways/<?=$item->title ?>.png" alt="<?=$item->title ?>" class="img-fluid w-75">
                                        <span class="d-block pt-2 font-size-13"><?php if ($item->title == "pay-later") { } else {} ?><?=str_replace('-', ' ', $item->title)?></span>
                                    </a>
                                </li>
                                


                                <?php if ($item->title == "installments") { ?> 

                                <!--<li class="nav-item  pt-4 col-lg-4 col-md-4 m-0 p-2 gateways_< ?=$item->title?>">-->
                                <!--    <a class="nav-link aaf < ?php if (str_replace('-', ' ', $item->title) == "payment with credit card") { echo "active"; }?>" 
                                            style="background:#fff;" data-toggle="tab" href="#< ?=$item->title ?>" payment-method="< ?=$item->title ?>" role="tab" aria-controls="< ?=$item->title ?>" 
                                               aria-selected="true" onclick="add_attributes_on_btn()">-->
                                <!--        <i class="la la-check icon-element"></i>-->
                                <!--        <img src="< ?=root.theme_url?>assets/img/gateways/< ?=$item->title ?>.png" alt="< ?=$item->title ?>" class="img-fluid w-75">-->
                                <!--        <span class="d-block pt-2 font-size-13">< ?php if ($item->title == "pay-later") { } else {} ?>< ?=str_replace('-', ' ', $item->title)?></span>-->
                                <!--    </a>-->
                                <!--</li>-->

                              <?php }else{ ?>

                                <!--<li class="nav-item pt-4 col-lg-4 col-md-4 m-0 p-2 gateways_< ?=$item->title?>">-->
                                <!--    <a class="nav-link aaf < ?php if (str_replace('-', ' ', $item->title) == "payment with credit card") { echo "active"; }?> " 
                                            style="background:#fff;" data-toggle="tab" href="#< ?=$item->title ?>" payment-method="< ?=$item->title ?>" role="tab" aria-controls="< ?=$item->title ?>" 
                                               aria-selected="true" onclick="remove_attributes_on_btn()">-->
                                <!--        <i class="la la-check icon-element"></i>-->
                                <!--        <img src="< ?=root.theme_url?>assets/img/gateways/<?=$item->title ?>.png" alt="< ?=$item->title ?>" class="img-fluid w-75">-->
                                <!--        <span class="d-block pt-2 font-size-13">< ?php if ($item->title == "pay-later") { } else {} ?>< ?=str_replace('-', ' ', $item->title)?></span>-->
                                <!--    </a>-->
                                <!--</li>-->

                              <?php } }?>  
                               <input class="form-check-input payment_gateway mx-auto" type="hidden" name="payment_gateway" id="payment_gateway" value="payment-with-credit-card" required>
                               <input class="form-check-input payment_gateway_data mx-auto" type="hidden" name="payment_gateway_data" value="<?php echo base64_encode(json_encode($app->payment_gateways[0])) ?>" required>
                               <input type="text" name="checkme" id="checkme" style="width:0px; height:0px;"  required />
                               <!--<input type="hidden" name="payment_gateway" required>-->
                       
                            </ul>
                            
                        </div><!-- end section-tab -->
                        
                        <!--///////////////////// Feras buttons ////////////////////-->
                           <div class="">
                                <div class="clearfix">
                                    
                                    <div class="">
                                        <div class="input-box">
                                            <div class="form-group">
                                                <div class="custom-checkbox">
                                                    <input type="checkbox" id="agreechb" onchange="document.getElementById('booking').disabled = !this.checked;" <?php if (dev == 1){echo "checked";}?> required>
                                                    <label for="agreechb"><?=T::bycontinuingyouagreetothe?> <a target="_blank" href="<?=root?>terms-of-use"> &nbsp; <?=T::termsandconditions?></a></label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="btn-box">
                                         <button class="theme-btn attr_for_tabby809 book" type="button" id="booking" name="booking" <?php if (dev == 1){} else{echo "disabled";}?>><?=T::confirmbooking?></button>
                                        </div>
                                    </div><!-- end col-lg-12 -->
                                    
                                  
                               </div>
                            </div><!-- end col-lg-12 -->
                           
                        <!--////////////////////// Feras button end ////////////////////-->
                        
                        <script type="text/javascript">

                        // $('a.aaf').click(function(){
                        //     var payment_method = $(this).attr('payment-method');
                        //     // alert(payment_method);
                        //     $('.payment_gateway').val(payment_method);
                        // });

                        //  function add_attributes_on_btn(){
                        //     $('.attr_for_tabby').removeAttr('type');
                        //     $('.attr_for_tabby').attr("type","button");
                        //     $('.attr_for_tabby').attr("onclick","submit_tabby_req()");
                        //  }
                        //  function remove_attributes_on_btn(){
                        //     $('.attr_for_tabby').removeAttr("type");
                        //     $('.attr_for_tabby').removeAttr("onclick");
                        //     $('.attr_for_tabby').attr("type","submit");
                        //     }

                        </script>
                       
                    </div><!-- end form-content -->
               
<script src="<?=root?><?=theme_url?>assets/js/bootstrap.min.js"></script>
  
</div>

 <div class="col-lg-12 p-2">
     <!--<input style="padding: 6px 44px" id="primaryPrevBtn3" class="btn btn-warning waves-effect">Prev</button>-->
       <!--<input style="padding: 6px 44px" id="AccordionPervBtn3" name="AccordionPervBtn3" class="AccordionPervBtn btn btn-warning waves-effect" value="Prev">-->
       <button oncklick="#" style="padding: 6px 44px" type="button" id="AccordionPervBtn3" name="AccordionPervBtn3" class="AccordionPervBtn btn btn-warning waves-effect">Prev</button>
 </div>                 
 
 <script>
//     $(document).ready(function(){
//         $('a[data-toggle="tab"]').on('show.bs.tab', function(e) {
//             localStorage.setItem('activeTab', $(e.target).attr('href'));
//         });
//         var activeTab = localStorage.getItem('activeTab');
//         if(activeTab){
//             $('#credit-card-tab a[href="' + activeTab + '"]').tab('show');
//             alert('feras');
//           //  $('#myTab a[href="' + activeTab + '"]').tab('show');
//         } else {
//           alert('nooo');
//         }
// });
    
    
    
      $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
          var target = $(e.target).attr("href"); // activated tab
          
           $("#checkme").val(target);
           $("#payment_gateway").val(target);
           
          // alert('ferassss');
           
           
        //  if ( target == 'tabby')
        //      {
        //       alert(target);
        //      }
    });
    
    
    
$( "#booking" ).click(function() {
    
  //  alert($("#payment_gateway").val());
    
    if($("#payment_gateway").val() == 'tabby')
    {
       tabby_check_fun();  
    } else if ($("#payment_gateway").val() == 'debit::credit-card-payment') {
       
        // alert('1111111');
         
         $('#registerSubmit22').attr('action', '<?=root?>payment/debit_credit_card_payment');
         $('#registerSubmit22')[0].submit();
       //  document.getElementById("registerSubmit22").submit();
         
         
         
        // // submit();
         
        // $("#registerSubmit22").submit(function(event) {
        //       event.preventDefault(); // Prevent default form submission
        //       // Your code here
        //       alert('1111111weeeeeee');
        //     });
         
        //  //$( "#registerSubmit22" ).submit(); 
    } else if ($("#payment_gateway").val() == 'debit::credit-card-installment') {
      // alert('33333');
         $('#registerSubmit22').attr('action', '<?=root?>payment/debit_credit_card_installments');
         $('#registerSubmit22')[0].submit();
         
         
         //$( "#registerSubmit22" ).submit(); 
       //  alert('44444');
    } else {
      $( "#registerSubmit22" ).submit();  
    }
});
    

function tabby_check_fun()
{
                $("#spinner-div").show(); //Load button clicked show spinner

                $.ajax({
                        url: '<?=root?>payment/tabby_api',
                        type: 'POST',
                        data: $("#registerSubmit22").serialize(),
                        success: function(data) {
                             var jsonData = JSON.parse(data);
                             console.log(jsonData);
                                 if (jsonData.available_products == 'allowed') {
                                        window.location = jsonData.web_url;
                                    } else {
                                       alert('<?= T::tabby_message?>');
                                       $("#alert-div").show(1000);
                                    }
                        }, complete: function () {
                            $("#spinner-div").hide(); //Request is complete so hide spinner
                          },
                          error: function(error) {
                             alert(error);    
                             console.log(error);
                            }
                    });
}
    
    
</script>                   
                  

 </div>
</div><!--accordion-->     


</div><!-- end form-box -->